//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibware.Template.Presentation.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigurationKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dibware.Template.Presentation.Web.Resources.ConfigurationKeys", typeof(ConfigurationKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationEnvironment.
        /// </summary>
        internal static string ApplicationEnvironment {
            get {
                return ResourceManager.GetString("ApplicationEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationTitle.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationVersion.
        /// </summary>
        internal static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrandName.
        /// </summary>
        internal static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultThemeName.
        /// </summary>
        internal static string DefaultThemeName {
            get {
                return ResourceManager.GetString("DefaultThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleName_AdministratorUser.
        /// </summary>
        internal static string RoleName_AdministratorUser {
            get {
                return ResourceManager.GetString("RoleName_AdministratorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleName_MainUser.
        /// </summary>
        internal static string RoleName_MainUser {
            get {
                return ResourceManager.GetString("RoleName_MainUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleName_SuperUser.
        /// </summary>
        internal static string RoleName_SuperUser {
            get {
                return ResourceManager.GetString("RoleName_SuperUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleName_UnknownUser.
        /// </summary>
        internal static string RoleName_UnknownUser {
            get {
                return ResourceManager.GetString("RoleName_UnknownUser", resourceCulture);
            }
        }
    }
}
