//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibware.Template.Presentation.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dibware.Template.Presentation.Web.Resources.PageText", typeof(PageText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was successfully changed.
        /// </summary>
        public static string ChangePasswordConfirmed {
            get {
                return ResourceManager.GetString("ChangePasswordConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and confirmation token in the boxes below.
        /// </summary>
        public static string ConfirmAccount {
            get {
                return ResourceManager.GetString("ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering for an account. To complete registration we need you to confirm the email address you registered with us. An email with a registration confirmation code has been sent to the email address that you supplied. Please check your email account, follow the instructions in the email..
        /// </summary>
        public static string ConfirmAccountCheckEmail {
            get {
                return ResourceManager.GetString("ConfirmAccountCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or please click the link below to take you a page where you can manually enter your confirmation token..
        /// </summary>
        public static string ConfirmAccountCheckEmail2 {
            get {
                return ResourceManager.GetString("ConfirmAccountCheckEmail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but something has gone wrong when you have tried to confirm your account..
        /// </summary>
        public static string ConfirmAccountFailure {
            get {
                return ResourceManager.GetString("ConfirmAccountFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has now been confirmed. Please use the link below to take you to the login screen..
        /// </summary>
        public static string ConfirmAccountSuccess {
            get {
                return ResourceManager.GetString("ConfirmAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been logged out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select as complicated a password as you can manage to remember. Please do not use the same password for this website as you use for other online accounts where security is paramount; for example your email account or your online banking. If find you have trouble remembering many passwords and you currently use one &quot;normal&quot; password for many sites, maybe consider adding some text to the start or end of your &quot;normal&quot; password for this site so that it becomes that becomes unique for this site..
        /// </summary>
        public static string PasswordAdvice {
            get {
                return ResourceManager.GetString("PasswordAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in with your new password.
        /// </summary>
        public static string PleaseLogInWithNewPassword {
            get {
                return ResourceManager.GetString("PleaseLogInWithNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the form below to recover your password via email.
        /// </summary>
        public static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We apologise if the registration process appears long and complicated, but we only have the best interests of your security in mind..
        /// </summary>
        public static string RegistrationSecurityApology {
            get {
                return ResourceManager.GetString("RegistrationSecurityApology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been logged out..
        /// </summary>
        public static string YouHaveBeenLoggedOut {
            get {
                return ResourceManager.GetString("YouHaveBeenLoggedOut", resourceCulture);
            }
        }
    }
}
